---
title: "R Notebook"
output: html_notebook
---


```{r}
library(ChIPseeker)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene
library(clusterProfiler)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.
```{r}
getwd()
#setwd("./projects/lb-OCT4-NANOG-ChIP-SEQ/")
```

```{r}
peakFile = "./macs_out_highQuality/NANOG_ChIP_peaks.narrowPeak"
peakFile2 = "./macs_out_highQuality/OCT4_ChIP_peaks.narrowPeak"
peak_nanog <- readPeakFile("./macs_out_highQuality/NANOG_ChIP_peaks.narrowPeak",header=0)
peak_oct4 <- readPeakFile("./macs_out_highQuality/OCT4_ChIP_peaks.narrowPeak",header=0)
peak_nanog
```

```{r}
covplot(peak_oct4, weightCol="V5")
```

```{r}
peakAnno <- annotatePeak(peakFile, tssRegion=c(-3000, 3000),
                         TxDb=txdb, annoDb="org.Hs.eg.db")

```



```{r}
par(ps = 12, cex =1, cex.main = 1)
plotAnnoPie(peakAnno)
```

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).
